### ISSUE TITLE
3DCanvas: optimize camera controls

### ISSUE THREAD

**Issue by filippomc** [MetaCell/geppetto-meta#156]
Camera controls are given as a prop (cameraOptions) from the parent component, causing a full component rerender while, for instance, zooming in.
Want to keep the ability to set the camera from the outside but still avoiding the component rerendering on camera changes: camera options as a prop allow to easily save and recover a session.

Some possible strategies:
 * use the props only on mount, ignore otherwise (shouldComponentUpdate logic)
 * debounce camera changes (say, save the state only once each second). This is a camera handler logic (which is provided by the parent component, so we could provide some bread and butter and examples). This would make also external state more efficient (e.g. redux)
 * use the component inside session and suggest to use the widget export session capability when state persistence is needed (https://github.com/MetaCell/geppetto-meta/blob/c3c45c6dafd258fc6e7103529ead0cc9a72cb2a3/geppetto.js/geppetto-client/js/common/layout/model.ts#L46)
 * ...

**Comment by afonsobspinto** [comment]
> causing a full component rerender while, for instance, zooming in.

I don't think this is entirely true, at least not for class components, the zooming and movement can be / is done directly in the threeJS scene so the canvas component itself doesn't (need to) update. However, because of this, in the next update of the canvas (whatever the reason that triggers it) now we need to synchronize the props to the current state of the camera otherwise the scene will jump to a previous camera position. We can do that using the camera handler which is a callback that receives the changes to the camera done through Threejs.

With that said, I don't like this approach either as stated on #67 so I'm +1 for a change

> We (now) control the camera (position, rotation) through props (camOptions).
> However, the movement in the scene doesn't go through the canvas component but rather affects the scene directly (using Threejs TrackballControls).
> If we don't keep track of the cameraUpdates (using the camera handler) future renders of the canvas component will pass a past position in the camOptions props (making the camera jump to a previous place)
> I can see this being problematic

**Comment by filippomc** [comment]
I agree now that I understand more it's a choice of the parent component to put the handler result on the state. I was getting that reloading the component was needed because of the other issue on #157. Closing
