### ISSUE TITLE
Check Resize detector why it's firing a react rerender of the canvas

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/geppetto-meta#159]
Atm the resize detector is firering a react rerender of the elements (canvas) of a tab after the tab is created.
This is a strange behaviour since the tab is created so why "resize" a created element. As you can see in the image the width / height is triggering the resize detector.

Please check why this happens.

![rerender_from_resizedetector](https://user-images.githubusercontent.com/124044/133741147-390a2133-d67d-402e-afef-1ee297e3e254.png)

**Comment by filippomc** [comment]
The resize detector is necessary to update the scenes when the browser window or the tabs are resized. Without the resize detector, we are not able to fit a 3d scene into the tab.
I guess the double resize is due to the following workflow:
 1. a new widget is created
 2. the layout manager adds a tab
 3. the widget factory initializes the component inside the tab
 4. After the component is initialized the tab changes size, so the resize is detected
 5. The component rerenders

Have to check if between the 3 and 5 renders there is a real change in size. If not, we are able to debounce the resize event someway. If yes, the second rerender is actually needed, so the main point would be to save time in the first render.

**Comment by zsinnema** [comment]
@filippomc why is the tab changing size in step 4? the component should fit the size of the tab so the tab size won't change

**Comment by filippomc** [comment]
I suspect that the tab will be sized after the first component rendering. Before that moment, the size would be 0.

**Comment by zsinnema** [comment]
may be the size of the tab should initial be 100% of the size the element it's in
