### ISSUE TITLE
Optimize rendering of the 3d scene after an instance property is changed

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/geppetto-meta#160]
Atm the 3d scene is recreated when there is a change of one of the properties of a geppetto instance in a scene (e.g. the color of the instance).

Since there is no change in the (number, obj / gltf / ..., ) of the instances (3d objects) the already created 3d objects can be reused saving the computation time.

Filippo already had a quick look and these source lines are interesting to look at:

[https://github.com/MetaCell/geppetto-meta/blob/9432ac42018391d32c603902032948c8f6d87353/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L64
](https://github.com/MetaCell/geppetto-meta/blob/9432ac42018391d32c603902032948c8f6d87353/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L64
)
[https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/ThreeDEngine.js#L686](https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/ThreeDEngine.js#L686)

**Comment by enicolasgomez** [comment]
@ddelpiano @filippomc after adding the color change component to the showcase and digging into the problem here are my thoughts:

- comparing props vs prevProps inside Canvas component is not enough for calling ThreeDEngine.update(), as like in ColorChange, only setting a differnent canvas background would trigger the trasversal
- shouldEngineTraverse shouldn't be a Canvas responsability but it should be checked by the engine itself, 
- worst case, expose this parameter to the client so he has the responsability of controlling wether to trasverse or not

I would propagate a `needTrasversal` parameter from the MeshFactory to the ThreeDEngine that in case of any update will do manage the trasversal accordingly but I think the real problem is having Canvas responsible of the engine traversal.

**Comment by zsinnema** [comment]
see also #163
