### ISSUE TITLE
transparency on instances when this is not specified

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-meta#346]
as reported during the netpyne call

**Comment by Muhaddatha** [comment]
what branch of Geppetto is this happening on ?
In out netpyne internal sprint meeting you said that this bug happens when there aren't any opacity values set.
So, I am trying to replicate it in the showcase by removing default opacities form the instances in the `AuditoryCortextExample.js` . I do that by removing all the a values in color rgba's [here](https://github.com/MetaCell/geppetto-meta/blob/543f4f0855f45d2ae3dda3090e056aa6592f3e9a/geppetto.js/geppetto-ui/src/3d-canvas/showcase/examples/AuditoryCortexExample.js#L13).
But opacity looks fine. :thinking_face: I'm using the development branch of Geppetto.

![image.png](https://images.zenhubusercontent.com/6092c4168a6d77eedd5f4505/25cf6301-f154-4017-9672-ef2ef22859a8)

**Comment by ddelpiano** [comment]
tested this in netpyne and the values was taken from a constant, closing this.
