### ISSUE TITLE
DICOM component replacement research 

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/geppetto-meta#416]
Check for a new library that would be compatible with same features we are using from amijs 

AmiJS (old, needs replacement):
https://github.com/FNNDSC/ami

Check showcase DICOM component to understand the API and match any new library.

Consider: react, community, support, etc.

Consider this:

https://medevel.com/14-best-browser-web-based-dicom-viewers-projects/

Finally, branch a POC with the new library, using the existing data feed from the REACT component that already exists.

**Comment by afonsobspinto** [comment]
Same as #395

**Comment by ddelpiano** [comment]
we have a shared requirement here, VFB wants to see volumetric data (3d volumes) from their NRRD files, so if we agree on a viewer that can handle that I think we can take part of this card within VFB.
Thx

**Comment by ddelpiano** [comment]
for the first iteration, could we give it a try to these 2 candidates?

1. https://github.com/FNNDSC/ami
2. https://github.com/bcn-medtech/rocket_viewer
3. continue what done in https://codepen.io/jrmartin/pen/KKRXGjp (POC developed by Jesus), leave this as last since I think these are not the only requirements will come for this card.

NRRD files: 
- https://v2.virtualflybrain.org/data/VFB/i/0010/12vj/VFB_00101567/volume.nrrd
- https://v2.virtualflybrain.org/data/VFB/i/0010/1567/VFB_00101567/volume.nrrd
- https://v2.virtualflybrain.org/data/VFB/i/0010/101b/VFB_00101567/volume.nrrd

Main goals of this card:
- being able to display the volumetric representation of these data.
- being able to mesh these data into the same viewer (so load all of them together).

**Comment by ddelpiano** [comment]
Best candidates so far:

- https://ohif.org/
- http://rii-mango.github.io/Papaya/
- https://github.com/herrmannlab/dicom-microscopy-viewer

**Comment by filippomc** [comment]
Outcome of my research for history: 
- OHIF is a full bundled application, could not find a simple way to extract only the dicom viewer
- Papaya is also kind of a full application but it's functionality wise only a nice and lean dicom viewer. But it's written in base old javascript with a strong assumptions on having only one viewer attached to the window object. Another drawback is that without threejs don't know how to att other artifacts to the scene
- [dicom-microscopy-viewer](https://github.com/herrmannlab/dicom-microscopy-viewer) misses a lot of features and does not bundle different formats loaders.
