### ISSUE TITLE
Finalize redux refactoring

### ISSUE THREAD

**Issue by filippomc** [MetaCell/geppetto-meta#93]
The redux refactoring is merged with this pr: https://github.com/MetaCell/geppetto-meta/pull/91

Some more work is needed in order to test it within the geppetto-meta codebase. The way I suggest to proceed is by creating a blueprint application (frontend only) that uses the layout system provided by the above refactoring.

Also removing old control logic can help a lot in making the platform usable with the new paradygm.

**Comment by lrebscher** [comment]
**LayoutManager & FlexLayout**

- [ ] root node must have id "root" -> this must be documented somewhere! (*LayoutManager.tsx::createTabSet*)
- [ ] document newWidget actions, what property means what? Not clear to me

* [ ] opinionated *leftPanel* logic in LayoutManger.tsx -> why + documentation
* [ ] Instead of "this.store = store;" why not use connect or write functional component & use `useStore`? (*LayoutManager.tsx*)
* [ ] Need callback or state update to get layout component when LayoutManager was configured. Have to use workaround atm.
* [ ] FlexLayout doesn't support functional components or withStyles
* [ ] 'Name' argument for Widget to set tab title should be explicitly passed to addWidget
* [x] LoadingSpinner should not expect `GEPPETTO` to be present, no component should expect this!
* [ ] Catch edge cases of LayoutManager actions, e.g. minimize widget when widget does not exist

**Other**

* [ ] Can *ComponentFactory*  be removed?
* [ ] Remove User Controller?
* [ ] Remove Experiments feature completely?
* [ ] Remove GEPPETTO.Flows?

**Package**

* [ ] Transform *.less* to *css* (main.js less import) -> not every project has less set up! Actually no CRA project has by default!
* [ ] Move LoadingSpinner to geppetto-ui

**Comment by lrebscher** [comment]
Bugs
* [ ] (1) Add Widget by using button, (2) remove widget by clicking on remove tab icon -> Crash
